### ISSUE TITLE
Inconsistent behavior on positive and negative Float/Double zeros 

### ISSUE THREAD

**Issue by glguy** [jberryman/hashabler#6]
This library appears susceptible to the same problem as discovered on the `hashable` package

https://github.com/tibbe/hashable/issues/116

**Comment by jberryman** [comment]
Thanks for pointing this out! I'll try to follow the discussion in that ticket

**Comment by jberryman** [comment]
@glguy I haven't seen what hashable authors have been discussing on IRC, but I'm not convinced those should hash to the same value. Those values have an identical `Eq` instance, but are in fact distinguishable (with `isNegativeZero`) and supposedly may have different behaviors under different operations. 

What do you think? Do you know of any other hashing libraries that normalize negative zero? I definitely think a comment is warranted at least.

**Comment by danielwaterworth** [comment]
If you expect `sort (nub x) == sort (HashSet.toList (HashSet.fromList x))`, then they should hash to the same value.

**Comment by jberryman** [comment]
Right, you can spell that all sorts of ways. But there are arguments to be made that `instance Eq Float` is broken or shouldn't even exist. And I'd be worried if I saw `sort (nub (x::Float))` in real code. 

At least a hash over the standard IEEE format bytes of a float is well-defined. Furthermore it's easier for users to `newtype` wrap a `Float` and write a normalized hash instance for that than the other way around.

**Comment by jberryman** [comment]
Although maybe the real question is whether we want to promise to match `Eq` (and tell users their instances should respect that as a law as well). Currently I don't promise that at all, but I at least see the benefit in that hash-based maps would work the same as Ord-based ones.

**Comment by jberryman** [comment]
This may be resolved one way or the other looking at : #8 and  in particular https://github.com/jberryman/hashabler/issues/8#issuecomment-258643797 . It's a priority to me that we get the best compatibility between the same code compiled to JS and machine code.
